version: "3.7"

networks:
  app_bridge:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - app_bridge

  nginx:
    image: nginx:1.15.0
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_bridge

  mysql:
    image: mysql:5.7
    container_name: "mysql"
    hostname: "docker_mysql"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
    ports:
      - "13306:3306"
    networks:
      - app_bridge
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
